### ISSUE TITLE
SensorControl fails first time after instrument plugged in

### ISSUE THREAD

**Issue by rdpoor** [rdpoor/cp#45]
On Windows, after you plug in an instrument and launch SensorControl, it will fail with "instrument not found" and then close the windows.  Subsequent launches of SensorControl work properly.

**Comment by rdpoor** [comment]
The cause: on Mac, the USB interface starts out powered up.  On Windows, the USB interface starts powered down, and doesn't power up until SensorControl expressly calls instrument().power_up().

The fix: add an explicit call to power_up() as follows:
```
    def process_loop(self):
        self.instrument().power_on()
        while True:
            self.instrument().assure_interactive_mode()
            self.process()
```

**Comment by rdpoor** [comment]
The fix was somewhat more detailed than what's shown above.  Re-opening.

**Comment by rdpoor** [comment]
Traced the problem to the low-level Windows read() function -- for reasons unknown, it wasn't returning data from the instrument.  And if I re-started the program without quitting pdb, the problem persisted: I had to quit out of pdb and restart before the read() function would return data.

On a hunch, I tried closing and re-opening the serial port (if the first ping() attempt failed).  This worked, so it's a reasonable workaround.

Marking fixed.

**Comment by SensorexNPD** [comment]
Still seeing this on my machine.

**Comment by rdpoor** [comment]
Peculiar.  I tested it on Windows 10 / 64 bit.  Is that your environment
too?  And just to make sure: When you boot SensorControl, does it announce
v1.6b as follows:

    SensorControl v1.6b: Copyright © 2018 Sensorex Corporation, all rights
reserved.

?
